name: brain-vs-brawn
version: 0.1.0.0
github: "luxo-ai/brain-vs-brawn"
license: BSD3
author: "Luis Serazo"
maintainer: "luxo.ai@protonmail.me"
copyright: "2022 Luis Serazo"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/luxo-ai/brain-vs-brawn#readme>

dependencies:
  - base >= 4.7 && < 5
  - regex-posix
  - regex-pcre

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  brain-vs-brawn-exe:
    main: Main.hs
    # source-dirs:
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brain-vs-brawn
